export const LOAD_BLOGGER = 'LOAD_BLOGGER';
export const GET_BLOGGER = 'GET_BLOGGER';
export const SEARCH_BLOGGER = 'SEARCH_BLOGGER';
export const DELETE_BLOGGER = 'DELETE_BLOGGER';
export const ADD_BLOGGER = 'ADD_BLOGGER';
export const EDIT_BLOGGER = 'EDIT_BLOGGER';
